# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: lithia-macos
    main: ./app/lithia
    env:
      - CGO_ENABLED=1
    ldflags: &build-ldflags
      - -s -w -X github.com/vknabel/lithia/info.Version={{.Version}}
      - -X github.com/vknabel/lithia/info.Commit={{.Commit}}
      - -X github.com/vknabel/lithia/info.Date={{.Date}}
      - -X github.com/vknabel/lithia/info.BuiltBy=goreleaser

    goos:
      # - linux
      # - windows
      - darwin
  # requires cross-compiler
  # brew install FiloSottile/musl-cross/musl-cross
  # brew reinstall FiloSottile/musl-cross/musl-cross --with-aarch64
  # brew install mingw-w64
  - id: lithia-x-linux-amd64
    main: ./app/lithia
    ldflags: *build-ldflags
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
    goos:
      - linux
    goarch:
      - amd64
  - id: lithia-x-linux-arm64
    main: ./app/lithia
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-musl-gcc
    ldflags: *build-ldflags
    goos:
      - linux
    goarch:
      - arm64
  - id: lithia-x-windows-amd64
    main: ./app/lithia
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    ldflags: *build-ldflags
    goos:
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - stdlib
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: lithia
    tap:
      owner: vknabel
      name: homebrew-lithia
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    license: "MIT"
    folder: Formula
    install: |
      bin.install "lithia"
      prefix.install "./stdlib"

dockers:
  - image_templates:
      - "vknabel/lithia:latest"
      - "vknabel/lithia:{{ .Tag }}"
      - "vknabel/lithia:v{{ .Major }}"
      - "vknabel/lithia:v{{ .Major }}.{{ .Minor }}"
    # different approach needed in future
    # actually goreleaser should be used to copy the binaries
    # -> only the second stage
    extra_files:
      - app
      - ast
      - external
      - info
      - langsrv
      - parser
      - reporting
      - resolution
      - runtime
      - stdlib
      - testing
      - world
      - go.mod
      - go.sum
      - lithia.go
